# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dengue_linebot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineuser',
            old_name='user_mid',
            new_name='user_id',
        ),
    ]
