# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengue_linebot', '0002_auto_20161017_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('user_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UnrecognizedMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('user_id', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='picture_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='status_message',
            field=models.TextField(blank=True),
        ),
    ]
