# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengue_linebot', '0003_auto_20161026_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.TextField()),
                ('speak_time', models.DateTimeField()),
                ('message_type', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
