# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dengue_linebot', '0004_messagelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unrecognizedmsg',
            name='message',
        ),
        migrations.RemoveField(
            model_name='unrecognizedmsg',
            name='user_id',
        ),
        migrations.AddField(
            model_name='unrecognizedmsg',
            name='message_log',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='unrecognized_message_log', to='dengue_linebot.MessageLog'),
            preserve_default=False,
        ),
    ]
