# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dengue_linebot', '0010_auto_20161122_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseToUnrecogMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('unrecognized_msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proper_response', to='dengue_linebot.UnrecognizedMsg')),
            ],
        ),
        migrations.AlterField(
            model_name='botreplylog',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_reply_log', to='dengue_linebot.LineUser'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_log', to='dengue_linebot.LineUser'),
        ),
    ]
