# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dengue_linebot', '0015_auto_20161207_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsetounrecogmsg',
            name='unrecognized_msg',
        ),
        migrations.AddField(
            model_name='responsetounrecogmsg',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsetounrecogmsg',
            name='unrecognized_msg_content',
            field=models.TextField(default='NULL', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botreplylog',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_reply_log', to='dengue_linebot.LineUser'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_log', to='dengue_linebot.LineUser'),
        ),
    ]
